server:
  port: 8080

management: 
  endpoints:
    web:
      exposure:
        include: health,prometheus,metrics
  endpoint:
    prometheus:
      enabled: true
    health:
      probes:
        enabled: true  

spring:
  cloud:
    config:
      enabled: true
  kafka:
    bootstrap-servers: kafka-1:9092,kafka-2:9092,kafka-3:9092
    consumer:
      group-id: events-processor-group
      enable-auto-commit: false
      auto-offset-reset: earliest
    listener:
      ack-mode: MANUAL
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

kafka:
  topic:
    ok: iot-events-ok
    alert: iot-events-alert
