spring:
  kafka:
    bootstrap-servers: kafka-1:9092,kafka-2:9092,kafka-3:9092
    consumer:
      group-id: health-alert-manager-group
      auto-offset-reset: latest

management:
  endpoints:
    web:
      exposure:
        include: prometheus,health
