server:
  port: 8080

mqtt:
  broker: tcp://mqtt-broker:1883
  topic: iot-events
  client-id: iot-events-bridge

kafka:
  bootstrap-servers: kafka-1:9092,kafka-2:9092,kafka-3:9092
  topic: iot-raw-events
