apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
  namespace: espfog-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
        - name: config-server
          image: docker-vm:8085/docker-hosted/config-server:latest
          ports:
            - containerPort: 8888
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8888
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8888
            initialDelaySeconds: 15
            periodSeconds: 10

    
---
apiVersion: v1
kind: Service
metadata:
  name: config-server
  namespace: espfog-services
spec:
  selector:
    app: config-server
  ports:
    - port: 8888
      targetPort: 8888
