apiVersion: apps/v1
kind: Deployment
metadata:
  name: iot-events-bridge
  namespace: espfog-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iot-events-bridge
  template:
    metadata:
      labels:
        app: iot-events-bridge
    spec:
      containers:
        - name: iot-events-bridge
          image: docker-vm:8085/docker-hosted/iot-events-bridge:latest
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: iot-events-bridge-hpa
  namespace: espfog-services
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: iot-events-bridge
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
