apiVersion: apps/v1
kind: Deployment
metadata:
  name: iot-events-bridge
  namespace: espfog-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iot-events-bridge
  template:
    metadata:
      labels:
        app: iot-events-bridge
    spec:
      hostAliases:
      - ip: 192.168.122.136
        hostnames:
        - kafka-1
      - ip: 192.168.122.121
        hostnames:
        - kafka-2
      - ip: 192.168.122.69
        hostnames:
        - kafka-3      
      - ip: 192.168.122.81
        hostnames:
        - mqtt-broker     
      containers:
        - name: iot-events-bridge
          image: docker-vm:8085/docker-hosted/iot-events-bridge:latest
          ports:
            - containerPort: 8080
          resources:
            requests: 
              memory: "256Mi" 
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10


---
apiVersion: v1
kind: Service
metadata:
  name: iot-events-bridge
  namespace: espfog-services
spec:
  selector:
    app: iot-events-bridge
  ports:
    - port: 8080
      targetPort: 8080
