apiVersion: apps/v1
kind: Deployment
metadata:
  name: events-processor
  namespace: espfog-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: events-processor
  template:
    metadata:
      labels:
        app: events-processor
    spec:
      hostAliases:
      - ip: 192.168.122.136
        hostnames:
        - kafka-1
      - ip: 192.168.122.121
        hostnames:
        - kafka-2
      - ip: 192.168.122.69
        hostnames:
        - kafka-3      
      containers:
        - name: events-processor
          image: docker-vm:8085/docker-hosted/events-processor:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "256Mi" 
              cpu: "100m"       
            limits:
              memory: "512Mi"
              cpu: "500m"
