apiVersion: apps/v1
kind: Deployment
metadata:
  name: health-alert-manager
  namespace: espfog-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: health-alert-manager
  template:
    metadata:
      labels:
        app: health-alert-manager
    spec:
      containers:
        - name: health-alert-manager
          image: docker-vm:8085/docker-hosted/health-alert-manager:latest
          ports:
            - containerPort: 8081
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: health-alert-manager-hpa
  namespace: espfog-services
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: health-alert-manager
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
