apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: events-processor-keda
  namespace: espfog-services
spec:
  scaleTargetRef:
    name: events-processor
  pollingInterval: 30
  cooldownPeriod: 300
  minReplicaCount: 1
  maxReplicaCount: 20
  triggers:
    - type: kafka
      metadata:
        bootstrapServers: 192.168.122.136:9092,192.168.122.97:9092,192.168.122.37:9092
        topic: iot-raw-events
        consumerGroup: events-processor-group
        lagThreshold: "100"
